### ISSUE TITLE
Cli export of markdown is broken

### ISSUE THREAD

**Issue by adius** [jsonresume/resume-cli#96] opened 2015-02-09 08:42 UTC
```
$ resume export --format md resume.json
```

yields to this view:

```
Select file format for export
-------------------------
.html
.pdf
```

Btw: How can this break? Shouldn't you have some tests for it? ;-)

**Comment by poleveD** [comment] 2015-02-09 08:54
This is not broken. You must provide a file name for the export command. Please check the documentation again:
```resume export [fileName]```

**Comment by adius** [comment] 2015-02-09 09:00
I tried every possible combination of parameters and it still didn't work. I have absolutely no idea how this cli is supposed to be used. Great design ^^

**Comment by poleveD** [comment] 2015-02-09 09:03
Why don't you post the command that you tried?

**Comment by adius** [comment] 2015-02-09 09:05
First line of my first comment: ^^
> `$ resume export --format md resume.json`

**Comment by poleveD** [comment] 2015-02-09 09:15
Can you try this instead?
```resume export myresume.md```

**Comment by adius** [comment] 2015-02-09 09:22
As I said, I tried already every possible combination…
Yields to this view again:
```
Select file format for export
-------------------------
.html
.pdf
```

**Comment by poleveD** [comment] 2015-02-09 09:25
Can you try this? ```resume export myresume.html```

Possible that only the markdown format export is broken.

**Comment by adius** [comment] 2015-02-09 09:34
Yeah, both html and pdf work.
But is there no way to specify the input file? Does it always just assume you call it `resume.json`?
This should definitely be changed. Also it's not clear that it gets the format from the file-ending and you only have to specify the --format flag when the file-ending differs.

**Comment by poleveD** [comment] 2015-02-09 09:39
Yes, it always assumes that the input is resume.json. Agree that it could be parameterized as well. I will look into this.

**Comment by mchelen** [comment] 2015-04-06 21:29
I think the markdown export was added after the filename detection, so probably the `.md` extension needs to be added to the filename detection.

**Comment by chrisdotcode** [comment] 2015-11-12 23:53
(duplicate of #40)

**Closed by chrisdotcode** 2015-11-12 23:53 UTC
