### ISSUE TITLE
Theme error [bug]

### ISSUE THREAD

**Issue by santiph** [jsonresume/resume-cli#148] opened 2015-08-12 00:17 UTC
I'm trying to change the default theme of my resume to "elegant". I got a successful message, but when I open the browser, I see this error message: 
```
Theme returned an error.
TypeError: Cannot read property 'profiles' of undefined
    at Object.render (/home/ubuntu/theme-manager/themes/jsonresume-theme-elegant/0.9.11/index.js:109:33)
    at runTheme (/home/ubuntu/theme-manager/lib/theme.js:23:24)
    at /home/ubuntu/theme-manager/lib/theme.js:112:13
    at FSReqWrap.cb [as oncomplete] (fs.js:228:19)
```

Also, if I select "add theme" option, I see "Enter theme name: " in the console, but as soon as I type the first key, it returns to the console `~/Documents/resume$` waiting for the next command. I can't do anything.

**Comment by boreal** [comment] 2015-08-30 04:16
I get the same error when trying to export using the slick theme.

**Comment by mudassir0909** [comment] 2015-08-31 12:21
Looks like your resume json is lacking `basics` section(Although resume-cli doesn't allow invalid jsons). Can you verify that on `http://registry.jsonresume.org/{username}.json`?

**Comment by santiph** [comment] 2015-08-31 14:50
It's valid on my local environment. But if I try to download by appending the ".json" to my resume, I see no basic section in there

**Comment by mudassir0909** [comment] 2015-08-31 19:36
Strange! it should have been there. If your resume cli allowed that which means either the resume cli validations are changed or something broke. Most of the themes are built based on those validation assumptions.

**Comment by boreal** [comment] 2015-08-31 20:22
Approximately 25% of the themes cause the error above when running the export command

resume export resume.html -f html -t theme_name

The rest work fine and produce a valid HTML file. What's really odd is that I've been using the slick theme for weeks without issues. It just stopped working a couple days ago.

**Comment by spilledmilk** [comment] 2015-08-31 23:55
Having the same issue as @santiph. 

Another thing I noticed, I don't know if you've run across it too, but at some point when I tried to update the "basics" summary section, even after publishing it wouldn't change. Everything else I tried editing did though.

**Comment by heydonovan** [comment] 2015-09-02 15:57
Yup! I'm running into the same bug, even using the default resume made with `resume init`.

**Comment by boreal** [comment] 2015-09-08 23:29
So my workaround for this issue is that I load the resume in my local online resume-editor, choose the slick theme and the resume looks fine so I copy and paste the HTML from there to my public resume.html. Extra steps are kinda yuck but it gives me the result I want. Why does it work using the resume-editor?

**Comment by JasonStoltz** [comment] 2015-09-09 16:29
I have this issue also. When I `resume publish` my resume ... the "basics" section appears to be stripped from my `.json` file, not sure why.

**Comment by chrisdotcode** [comment] 2015-11-12 23:47
(duplicate of jsonresume/registry-server#75)

**Closed by chrisdotcode** 2015-11-12 23:47 UTC
