### ISSUE TITLE
Build(failed) on travis-ci

### ISSUE THREAD

**Issue by PeterDaveHello** [jsonresume/resume-cli#145] opened 2015-08-02 13:03 UTC
Now all the builds failed ...

**Comment by chrisdotcode** [comment] 2015-11-12 20:11
Since random isn't really reproducible, I'm going to close this for now.

@PeterDaveHello , if this happens again/if I'm wrong, can you re-open this with an error log, please?

**Comment by PeterDaveHello** [comment] 2015-11-13 08:32
I think it's not only random now.

**Comment by PeterDaveHello** [comment] 2015-11-17 02:59
https://github.com/jsonresume/resume-cli/commit/45a521a24a4805f6977600fabf98049aaf4e3b57 make it passwd lol

**Comment by PeterDaveHello** [comment] 2015-11-17 03:06
Got it again: https://travis-ci.org/jsonresume/resume-cli/jobs/91519603

**Closed** 2015-11-17 03:08 UTC
Labels: bug, help wanted
