### ISSUE TITLE
Unable to delete account

### ISSUE THREAD

**Issue by kpsychwave** [jsonresume/resume-cli#178] opened 2015-11-29 01:32 UTC
Hi,

I have been trying to delete my account on http://registry.jsonresume.org/ using resume-cli but the CLI exits when I select the option. This is the output. I have tried it on Mac OS X and Ubuntu 14.04 with same results.

$ resume settings

```
 SETTINGS                       
 -------------------------      
 CHANGE THEME                   
 CHANGE PASSWORD                
 DELETE ACCOUNT                 
 ------------------------------ 
 EXIT                           
```

SELECTED: DELETE ACCOUNT

**Comment by thomasdavis** [comment] 2015-11-29 01:58
Could you email me at thomasalwyndavis@gmail.com and I will manually delete
in the mean time.

On Sun, Nov 29, 2015 at 12:32 PM, kpsychwave <notifications@github.com>
wrote:

> Hi,
>
> I have been trying to delete my account on http://registry.jsonresume.org/
> using resume-cli but the CLI exits when I select the option. This is the
> output. I have tried it on Mac OS X and Ubuntu 14.04 with same results.
>
> $ resume settings
>
>  SETTINGS
>  -------------------------
>  CHANGE THEME
>  CHANGE PASSWORD
>  DELETE ACCOUNT
>  ------------------------------
>  EXIT
>
> SELECTED: DELETE ACCOUNT
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsonresume/resume-cli/issues/178>.
>



-- 
Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com

**Comment by AntoineReneleau** [comment] 2015-12-14 22:24
Same here.
I deleted it by sending a HTTP DELETE to ```http://registry.jsonresume.org/account``` with payload
```
{"email":"mymail","password":"mypassword"}
```

**Comment by kpsychwave** [comment] 2015-12-20 11:20
Thanks the HTTP Delete did it!

**Comment by chrisdotcode** [comment] 2015-12-23 03:15
Issue resolved(?)

**Comment by AntoineReneleau** [comment] 2015-12-23 09:26
@chrisdotcode The issue isn't resolved. The ```resume delete``` command doesn't work. We had to send the DELETE request ourselves.

**Comment by chrisdotcode** [comment] 2015-12-23 09:50
My mistake. Thanks.

**Comment by RazzaFrazza** [comment] 2016-01-20 11:14
Guys can you remove my resume please. I've been trying to delete it for the last hour or two. The resume user is razzakun.

**Comment by RazzaFrazza** [comment] 2016-01-25 05:22
Guys this is still up... I can't delete my account. http://registry.jsonresume.org/razzakun

**Comment by thomasdavis** [comment] 2016-01-25 05:29
@RazzaFrazza deleted, sorry for delay.

**Comment by Callisto13** [comment] 2016-08-26 23:47
hey guys, i published a resume nearly two years ago and totally forgot about it. have tried curl deleting it but i keep getting not found and i cannot remember the email/password that i used. could you delete it for me please? http://registry.jsonresume.org/claudiaberesford thanks

**Comment by Callisto13** [comment] 2016-10-10 12:29
@RazzaFrazza this is still up http://registry.jsonresume.org/claudiaberesford and I can't get rid of it. Thanks

**Comment by thomasdavis** [comment] 2016-10-11 11:05
@Callisto13 sorry for the delay, I suck.

**Comment by Callisto13** [comment] 2016-10-11 12:17
@RazzaFrazza all gone! Thanks!!

**Comment by arianjinx** [comment] 2016-11-13 08:41
@thomasdavis hello please help me to delete my online resume http://registry.jsonresume.org/arianpradana, big big thanks.

**Comment by alnewkirk** [comment] 2016-11-17 17:57
Hi guys. I published a resume a while ago and I cannot remember the email/password either. The password reset option, as well as registering a new account with the same email, doesn't work from the command-line. Could someone please delete it for me? http://registry.jsonresume.org/alnewkirk

**Comment by butilities** [comment] 2017-02-09 01:31
You can delete your account from terminal with curl via the following line
` curl -H "Content-Type: application/json" -X DELETE -d '{"email":"youremailhere","password":"yourpasswordhere"}' http://registry.jsonresume.org/account`

If successful, you should be getting the following reply:
`{"message":"\nYour account has been successfully deleted."}`

**Comment by rkhambekar** [comment] 2017-03-03 21:28
@thomasdavis Please delete my online resume too.
https://registry.jsonresume.org/rohan-uday-khambekar

**Comment by snaheth** [comment] 2017-03-04 06:03
@thomasdavis Please delete my online resume @ https://registry.jsonresume.org/snaheth

**Comment by 0xcrypto** [comment] 2017-03-06 13:04
Please delete my resume too. I think I don't remember the password. https://registry.jsonresume.org/0xcrypto

```
Cannot DELETE /0xcrypto
```

**Comment by thomasdavis** [comment] 2017-03-07 03:52
@rkhambekar @0xcrypto Both your resumes are now deleted.

**Comment by git-toni** [comment] 2017-03-15 17:36
@thomasdavis I'd love mine deleted as well, some months ago you deleted the user account but the resume is still online it seems : /      http://registry.jsonresume.org/resume-toni
thank you!

**Comment by alexfulsome** [comment] 2017-03-18 06:46
@thomasdavis just realized mine was still up to. registry.jsonresume.org/alexfulsome. tried to delete it myself as those above have, but all my req's are timing out. please delete it. thanks.

**Comment by axelavargas** [comment] 2017-05-18 18:46
@thomasdavis Hi :),  please delete mine as well, I tried all the options (command line, curl, http) but nothing works [https://registry.jsonresume.org/axelav], in advance thank you for your help ^ ^.

**Comment by WorkHorseIndustries** [comment] 2017-06-15 04:19
Please delete mine as well. I'm sorry, I tried to send a curl to delete but it wasn't working replied with Cannot DELETE https://registry.jsonresume.org/alex-nimmer

**Comment by thomasdavis** [comment] 2017-06-15 04:26
@git-toni  @alexfulsome  @axelavargas @WorkHorseIndustries all deleted. Sorry for the delay.

**Comment by js345** [comment] 2017-06-29 02:53
@thomasdavis Could you please delete mine as well? http://registry.jsonresume.org/js345
Thank you!

**Comment by tilke** [comment] 2017-07-24 14:33
I cannot login to my account "tilke".  Since I can't reset the password could you please delete so I can recreate?

**Comment by dbeley** [comment] 2017-08-09 11:56
Hello I also would like to delete my resume. Can't find any way to do it as I've deleted the old repo and also changed my github username…

Could you please delete it manually ?
The address is http://registry.jsonresume.org/davidbeley

Thanks in advance !

**Comment by thrash4life** [comment] 2017-08-09 19:16
Howdy, I forgot my password and would like to delete my account too: http://registry.jsonresume.org/joshuasherer

**Comment by yogipatel** [comment] 2017-10-18 20:18
Please delete /yogi Thank you!

**Comment by adeelkhan** [comment] 2017-11-07 22:37
@thomasdavis Wanting to delete my resume too for while but couldn't because of forgot password. I would really appreciate if you can delete it thanks.
Delete  http://registry.jsonresume.org/adeelkhan

**Comment by gsrka** [comment] 2017-11-10 07:41
Hi guys,

I tried deleting my resume at http://registry.jsonresume.org/gsrkabhimanyu1using curl but getting this strange error. Could you please delete my account.

<pre>SyntaxError: Unexpected token &#39;<br> &nbsp; &nbsp;at parse (/root/registry-server/node_modules/body-parser/lib/types/json.js:83:15)<br> &nbsp; &nbsp;at /root/registry-server/node_modules/body-parser/lib/read.js:116:18<br> &nbsp; &nbsp;at invokeCallback (/root/registry-server/node_modules/raw-body/index.js:262:16)<br> &nbsp; &nbsp;at done (/root/registry-server/node_modules/raw-body/index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/root/registry-server/node_modules/raw-body/index.js:307:7)<br> &nbsp; &nbsp;at emitNone (events.js:86:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:188:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:975:12)<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:80:11)<br> &nbsp; &nbsp;at process._tickDomainCallback (internal/process/next_tick.js:128:9)</pre>


Thanks.

**Comment by ajfigueroa** [comment] 2017-11-11 02:06
@thomasdavis I know this doesn't scale well but I was wondering if you could delete mines as well? It'd really appreciate it.
http://registry.jsonresume.org/alexjfigueroa

**Comment by rlchu** [comment] 2017-11-11 22:56
same here, user 'rlchu' -- please!

**Comment by rlchu** [comment] 2017-11-11 23:30
@thomasdavis  ^^

**Comment by kahnwong** [comment] 2018-01-11 14:20
Could you please delete https://registry.jsonresume.org/kahnwong for me? Thank you in advance.

**Comment by rlchu** [comment] 2018-03-23 01:50
likewise -- http://registry.jsonresume.org/rlchu thank you!

**Comment by chandrewz** [comment] 2018-10-19 02:30
Can mine also be deleted: http://registry.jsonresume.org/chandrew

Tried a DELETE request and got a gateway timeout.

**Comment by dnasca** [comment] 2018-10-25 20:57
hi there, tried deleting with a DELETE req but timing out. 

can you please delete http://registry.jsonresume.org/derriknasca

thanks!

**Comment by toschneck** [comment] 2018-11-10 00:10
This approach doesn't solve the problem, but at least remover your data.
Create a empty example trough `init` and publish it:
```
mkdir /tmp/resume
cd /tmp/resume
resume init
resume publish
rm -rf /tmp/resume
```

**Comment by chrisdotcode** [comment] 2020-07-06 00:06
(Closing auto-manually because after 2 years, this might no longer be relevant. If this still does concern anyone, give me a holler.)

**Closed by chrisdotcode** 2020-07-06 00:06 UTC
