### ISSUE TITLE
Static file server

### ISSUE THREAD

**Issue by bmullan91** [jsonresume/resume-cli#91] opened 2015-01-24 22:38 UTC
Whilst developing my own theme, I came across the issue where the server wasn't reporting back my font located within the same directory (under /fonts/<font>). 

Looking at the code it's clear the server doesn't handle any routes, but simply outputs the same response. This makes it really simple, but very limiting.

Possible solutions:

**1.** Handling the routes in existing serve.js

```js
if (req.url === "/") {
  doExistingResumeStuff();
} else {
  doFileLookup();
}
```

This would be ugly.

**2.** Making `resume serve` start a static file server (eg [http-server](https://www.npmjs.com/package/http-server) etc).

To make this work:
- Move resume building logic out into a separate file.
- A watch command would be started, which would re-build an `index.html` file with the response from function above ^.

------

These are just my initial thoughts. I don't know the code base, and Im not even sure if this is feasible with existing logic / architecture without a large re-write.

Really I'd just like to open the discussion to possible solutions to this problem, and would be willing to help with fixes etc.

**Comment by thomasdavis** [comment] 2015-01-25 07:38
hey @bmullan91 thanks for all the information. The problem is, we don't have a way of handling external assets very easily at all. We have opted to make sure all assets are included inline or on external CDN's.

Because if a font is relative to the directory, we can't always anticipate what environment it will be in.

Are you able to use the font externally hosted?

**Comment by bmullan91** [comment] 2015-01-26 14:15
I don't see how that is a problem, or else I'm forgetting something obvious? The browser handles the asset lookup (could be remote, could be a relative path).

The theme directory should be a standalone webpage - containing all the asset's it requires. For example, say someone want's to use an image that's located in the directory or in my case a font. 

What I described in my previous comment would also allow someone to host their resume themselves, say on github pages, (ie without needing a server to render it) because the watch command would generate an `index.html` file.

**Closed** 2015-02-02 18:08 UTC

**Comment by thomasdavis** [comment] 2015-02-02 18:10
Seems that you were 100% correct. Going to try run it up with forever or pm2 and see how it works for hosting your own resume.
