### ISSUE TITLE
resume serve while developing a theme doesn't load index.js

### ISSUE THREAD

**Issue by hkdobrev** [jsonresume/resume-cli#412] opened 2020-11-10 21:48 UTC
I believe #367 broke a documented behaviour of the `resume serve` command.

When developing a theme one should be available to run `resume serve` inside the theme folder and that should load `index.js` from the current folder. Currently, it loads the default theme instead.

_Originally posted by @hkdobrev in https://github.com/jsonresume/resume-cli/pull/367#issuecomment-724986513_

**Comment by rbardini** [comment] 2020-11-11 09:37
Duplicate of #386.

**Closed by rbardini** 2020-11-11 09:37 UTC
Labels: duplicate
