### ISSUE TITLE
Cannot switch to old mode now

### ISSUE THREAD

**Issue by raybesiga** [jsonresume/resume-cli#146] opened 2015-08-03 10:48 UTC
Installed resume-cli and worked on the resume. I format the JSOn file right and run 'resume register'. When I run the 'resume publish' command, I get the following errors:

```javascript
SELECTED: Publish to your account.

To acquire login details use the command: `resume register`
If you already have an account, enter your login details below:

_stream_readable.js:729
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:729:11)
    at ReadStream.Readable.resume (_stream_readable.js:714:3)
    at new Interface (readline.js:142:9)
    at Object.exports.createInterface (readline.js:39:10)
    at read (/Users/raybesiga/.npm_modules/lib/node_modules/resume-cli/node_modules/read/lib/read.js:45:23)
    at /Users/raybesiga/.npm_modules/lib/node_modules/resume-cli/lib/publish/index.js:59:21
    at Menu.<anonymous> (/Users/raybesiga/.npm_modules/lib/node_modules/resume-cli/lib/publish/menu.js:33:7)
    at Menu.EventEmitter.emit (events.js:98:17)
    at Menu.ondata [as _ondata] (/Users/raybesiga/.npm_modules/lib/node_modules/resume-cli/node_modules/terminal-menu/index.js:215:18)
    at DestroyableTransform._transform (/Users/raybesiga/.npm_modules/lib/node_modules/resume-cli/node_modules/terminal-menu/index.js:50:18)
    at DestroyableTransform.Transform._read (/Users/raybesiga/.npm_modules/lib/node_modules/resume-cli/node_modules/terminal-menu/
```
Has anyone faced this issue? It happens for both 'resume serve' and 'resume publish'

**Comment by stdg11** [comment] 2015-08-07 15:21
Not with resume server and publish, however I do with resume settings.

```
SELECTED: ADD THEME

_stream_readable.js:730
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:730:11)
    at ReadStream.Readable.resume (_stream_readable.js:715:3)
    at new Interface (readline.js:142:9)
    at Object.exports.createInterface (readline.js:39:10)
    at read (/usr/local/lib/node_modules/resume-cli/node_modules/read/lib/read.js:45:23)
    at async.series.theme (/usr/local/lib/node_modules/resume-cli/lib/settings/index.js:26:15)
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:683:13
    at iterate (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:260:13)
    at async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:279:9)
    at _parallel (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:682:9)
    at Object.async.series (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:704:9)
    at /usr/local/lib/node_modules/resume-cli/lib/settings/index.js:19:17
    at Menu.<anonymous> (/usr/local/lib/node_modules/resume-cli/lib/settings/menu.js:55:5)
    at Menu.EventEmitter.emit (events.js:98:17)
    at Menu.ondata [as _ondata] (/usr/local/lib/node_modules/resume-cli/node_modules/terminal-menu/index.js:215:18)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/resume-cli/node_modules/terminal-menu/index.js:50:18)
```

**Comment by mshenfield** [comment] 2015-08-14 01:50
This looks like a duplicate of #138 - there's a more active discussion going on there.

**Comment by chrisdotcode** [comment] 2015-11-12 20:07
Centralizing discussion to #149 .

**Closed by chrisdotcode** 2015-11-12 20:07 UTC
